### PR TITLE
Quiz

### PR DESCRIPTION
**Pull request by kolinkovlad**
Quiz stable version

### CODE REVIEW

**Review by skhortiuk — CHANGES_REQUESTED** [review]
replace url to patch or re_patch in quiz/urls.py

**Comment by kolinkovlad** [comment]
> replace url to patch or re_patch in quiz/urls.py

it was replaced to re_path

**Review by skhortiuk — APPROVED** [review]

**Review by skhortiuk — CHANGES_REQUESTED** [review]
Fix conflicts

**Review by skhortiuk — DISMISSED** [review]

**Review by skhortiuk — CHANGES_REQUESTED** [review]
Fix conflicts

**Comment by kolinkovlad** [comment]
> Fix conflicts

fixed

**Pull request closed without merging**
